name: Deploy Shopify Theme

on:
  push:
    branches:
      - main   # ONLY deploy when main updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}
      SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@3.59.0 @shopify/theme

      - name: Deploy to LIVE theme
        run: shopify theme push --theme ${{ secrets.SHOPIFY_THEME_ID_LIVE }} --allow-live
